### ISSUE TITLE
Navigation slightly hidden on Chrome

### ISSUE THREAD

**Issue by Cmdv** [learn-javascript-courses/learn-javascript#1]
Hi, great free course looking forward to more.

The navigational menu was left slightly hidden on desktop screen on Chrome, seems fine on firefox and Safari.

![screen shot 2015-03-16 at 08 39 34](https://cloud.githubusercontent.com/assets/3036557/6662883/88cdbfac-cbb8-11e4-90f5-aa2ca02fd804.png)

I found that adding the following sorts out the issue :)
# page-container { position:inherit; }

**Comment by ericelliott** [comment]
Thanks for the report. We're aware of this issue, and the designer is working on it. =)

**Comment by Cmdv** [comment]
ah cool, adding (position: inherit) to #page-container css sorted it out for me.

cheers

**Comment by ericelliott** [comment]
Interesting.
